version: '3.8'

services:
  transcription-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=True
      - DEFAULT_MODEL=base
      - USE_FASTER_WHISPER=True
      - DEVICE=cpu
      - COMPUTE_TYPE=int8
      - MAX_FILE_SIZE_MB=25
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
      - ./temp:/app/temp
      - ./models:/app/models  # Para cachear modelos descargados
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Opcional: Redis para cache (si se necesita en el futuro)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped

  # Opcional: Base de datos para logs/estadísticas
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: transcription_db
  #     POSTGRES_USER: transcription_user
  #     POSTGRES_PASSWORD: transcription_pass
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   postgres_data:
