name: transcription-api
services:
  - name: api
    type: web
    instance_type: free  # Free tier: 0.1 vCPU, 512MB RAM
    regions:
      - fra  # Frankfurt (Europe)
    env:
      - ENVIRONMENT=production
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - HOST=0.0.0.0
      - PORT=8000
    ports:
      - port: 8000
        protocol: http
    health_check:
      http:
        path: /health
        port: 8000
      initial_delay_seconds: 30
      timeout_seconds: 10
      period_seconds: 30
      success_threshold: 1
      failure_threshold: 3
    scaling:
      min: 1
      max: 1  # Free tier limitation
    docker:
      dockerfile: Dockerfile
      target: runtime
    build:
      buildpack: docker
